name: Deploy docs/examples/* to demo hosting

on:
  release:
    types: [published]
    branches: [main]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Upload docs/examples/*
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: 107.180.58.30
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: docs/examples/
        server-dir: guitar-diagrams-js/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          testing.html
          js/testing.js
